server {
    listen 8080;

    location = / {
        root /usr/src/app;
        try_files /landing.html =404;
    }

    location /skypirates {
        alias /usr/src/app/;
        try_files $uri $uri/ /skypirates/index.html;
    }
}
