services:
  client:
    build:
      context: ./client
    ports:
      - "80:8080"
    environment:
      SERVER_HOST: server
      
  server:
    build:
      context: ./server  
    ports:
      - "3000:3000" 
