events {}

http {
    server {
        listen 81 ssl default_server;
        ssl_certificate /usr/src/app/certs/fullchain.pem;
        ssl_certificate_key /usr/src/app/certs/privkey.pem;

        location / {
            root /usr/src/app;
            index index.html;
        }
    }
}