events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        root /usr/src/app;
        index landing.html;

        location = / {
            add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
            try_files /landing.html =404;
        }

        location = /papers {
            add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
            try_files /papers.html =404;
        }

        location = /landing.html {
            add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        }

        location = /papers.html {
            add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        }

        location /papers/ {
            alias /usr/src/app/papers/;
            autoindex on;
        }

        location /images/ {
            alias /usr/src/app/images/;
            autoindex on;
        }

        # Handle any other requests to landing page content
        location / {
            try_files $uri $uri/ /landing.html;
        }
    }
}
